version: '2'
services:
  influxdb:
    image: influxdb:1.8.3
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "5"
  chronograf:
    image: chronograf:1.8.7
    ports:
      - '8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "5"
  telegraf:
    image: telegraf:1.17.1
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "5"
  speedtest:
    build:
      context: .
      dockerfile: Speedtest-Dockerfile
    container_name: speedtest
    volumes:
      - ./config.ini:/src/config.ini
    depends_on:
      - influxdb
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "5"
  grafana:
    image: grafana/grafana:7.5.1
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "5"
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
